// This file is auto-generated by @hey-api/openapi-ts

import { type Options, deleteConfig, getCurrentConfig, updateConfig, resetConfig, createConfig, switchConfig, getConfigSchema, getConfigUiSchema, getDefaultConfig, getWebSocketConnections, listFiles, openPath, readNfo, saveNfo, startScrape, scrapeSingleFile, createSymlink, addSubtitles, getActors, completeActors, checkCookies, getSiteUrls, setSiteUrl, startScrape2, stopScrape, getScrapeStatus, getScrapeResults, checkNetwork, getProxyStatus, cropImage, previewImage, addWatermark, getImageInfo, findMissing, moveVideos, cleanFiles, manageExtras, manageExtrafanartCopy, manageThemeVideos } from '../sdk.gen';
import { type UseMutationOptions, queryOptions, type DefaultError } from '@tanstack/react-query';
import type { DeleteConfigData, DeleteConfigError, GetCurrentConfigData, UpdateConfigData, UpdateConfigError, UpdateConfigResponse, ResetConfigData, ResetConfigResponse, CreateConfigData, CreateConfigError, SwitchConfigData, SwitchConfigError, SwitchConfigResponse, GetConfigSchemaData, GetConfigUiSchemaData, GetDefaultConfigData, GetWebSocketConnectionsData, ListFilesData, OpenPathData, OpenPathError, ReadNfoData, SaveNfoData, SaveNfoError, StartScrapeData, ScrapeSingleFileData, ScrapeSingleFileError, CreateSymlinkData, CreateSymlinkError, AddSubtitlesData, GetActorsData, CompleteActorsData, CheckCookiesData, GetSiteUrlsData, SetSiteUrlData, SetSiteUrlError, StartScrape2Data, StartScrape2Error, StartScrape2Response, StopScrapeData, GetScrapeStatusData, GetScrapeResultsData, CheckNetworkData, CheckNetworkError, CheckNetworkResponse, GetProxyStatusData, CropImageData, CropImageError, CropImageResponse, PreviewImageData, AddWatermarkData, AddWatermarkError, GetImageInfoData, FindMissingData, FindMissingError, MoveVideosData, MoveVideosError, CleanFilesData, ManageExtrasData, ManageExtrasError, ManageExtrafanartCopyData, ManageExtrafanartCopyError, ManageThemeVideosData, ManageThemeVideosError } from '../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../client.gen';

/**
 * 删除配置文件
 */
export const deleteConfigMutation = (options?: Partial<Options<DeleteConfigData>>): UseMutationOptions<unknown, AxiosError<DeleteConfigError>, Options<DeleteConfigData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DeleteConfigError>, Options<DeleteConfigData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await deleteConfig({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getCurrentConfigQueryKey = (options?: Options<GetCurrentConfigData>) => createQueryKey('getCurrentConfig', options);

/**
 * 获取当前配置
 */
export const getCurrentConfigOptions = (options?: Options<GetCurrentConfigData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCurrentConfig({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCurrentConfigQueryKey(options)
    });
};

/**
 * 更新配置
 */
export const updateConfigMutation = (options?: Partial<Options<UpdateConfigData>>): UseMutationOptions<UpdateConfigResponse, AxiosError<UpdateConfigError>, Options<UpdateConfigData>> => {
    const mutationOptions: UseMutationOptions<UpdateConfigResponse, AxiosError<UpdateConfigError>, Options<UpdateConfigData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await updateConfig({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const resetConfigQueryKey = (options?: Options<ResetConfigData>) => createQueryKey('resetConfig', options);

/**
 * 重置配置
 * 将当前配置重置为默认值
 */
export const resetConfigOptions = (options?: Options<ResetConfigData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await resetConfig({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: resetConfigQueryKey(options)
    });
};

/**
 * 重置配置
 * 将当前配置重置为默认值
 */
export const resetConfigMutation = (options?: Partial<Options<ResetConfigData>>): UseMutationOptions<ResetConfigResponse, AxiosError<DefaultError>, Options<ResetConfigData>> => {
    const mutationOptions: UseMutationOptions<ResetConfigResponse, AxiosError<DefaultError>, Options<ResetConfigData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await resetConfig({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createConfigQueryKey = (options: Options<CreateConfigData>) => createQueryKey('createConfig', options);

/**
 * 创建配置文件
 * 创建指定名称的配置文件
 */
export const createConfigOptions = (options: Options<CreateConfigData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createConfig({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createConfigQueryKey(options)
    });
};

/**
 * 创建配置文件
 * 创建指定名称的配置文件
 */
export const createConfigMutation = (options?: Partial<Options<CreateConfigData>>): UseMutationOptions<unknown, AxiosError<CreateConfigError>, Options<CreateConfigData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<CreateConfigError>, Options<CreateConfigData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createConfig({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const switchConfigQueryKey = (options: Options<SwitchConfigData>) => createQueryKey('switchConfig', options);

/**
 * 切换配置
 * 切换到现有的配置文件。
 */
export const switchConfigOptions = (options: Options<SwitchConfigData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await switchConfig({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: switchConfigQueryKey(options)
    });
};

/**
 * 切换配置
 * 切换到现有的配置文件。
 */
export const switchConfigMutation = (options?: Partial<Options<SwitchConfigData>>): UseMutationOptions<SwitchConfigResponse, AxiosError<SwitchConfigError>, Options<SwitchConfigData>> => {
    const mutationOptions: UseMutationOptions<SwitchConfigResponse, AxiosError<SwitchConfigError>, Options<SwitchConfigData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await switchConfig({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getConfigSchemaQueryKey = (options?: Options<GetConfigSchemaData>) => createQueryKey('getConfigSchema', options);

/**
 * 获取配置架构
 * 返回配置的JSON架构。
 */
export const getConfigSchemaOptions = (options?: Options<GetConfigSchemaData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getConfigSchema({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getConfigSchemaQueryKey(options)
    });
};

export const getConfigUiSchemaQueryKey = (options?: Options<GetConfigUiSchemaData>) => createQueryKey('getConfigUiSchema', options);

/**
 * 获取UI架构
 * 返回配置的UI架构。
 */
export const getConfigUiSchemaOptions = (options?: Options<GetConfigUiSchemaData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getConfigUiSchema({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getConfigUiSchemaQueryKey(options)
    });
};

export const getDefaultConfigQueryKey = (options?: Options<GetDefaultConfigData>) => createQueryKey('getDefaultConfig', options);

/**
 * 获取默认配置
 * 返回默认配置。
 */
export const getDefaultConfigOptions = (options?: Options<GetDefaultConfigData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getDefaultConfig({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getDefaultConfigQueryKey(options)
    });
};

export const getWebSocketConnectionsQueryKey = (options?: Options<GetWebSocketConnectionsData>) => createQueryKey('getWebSocketConnections', options);

/**
 * 获取所有 WebSocket 连接信息
 */
export const getWebSocketConnectionsOptions = (options?: Options<GetWebSocketConnectionsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getWebSocketConnections({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getWebSocketConnectionsQueryKey(options)
    });
};

export const listFilesQueryKey = (options: Options<ListFilesData>) => createQueryKey('listFiles', options);

/**
 * 列出文件和目录
 * 列出指定路径下的文件和目录. 仅允许访问 `SAFE_DIRS` 目录下的内容, `SAFE_DIRS` 可通过服务器环境变量 `MDCX_SAFE_DIRS` 设置. 指向 `SAFE_DIRS` 外目录的软链接本身可见, 但无法访问其内容.
 */
export const listFilesOptions = (options: Options<ListFilesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listFiles({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listFilesQueryKey(options)
    });
};

export const openPathQueryKey = (options: Options<OpenPathData>) => createQueryKey('openPath', options);

/**
 * 打开文件或文件夹
 * 在系统文件管理器中打开文件或文件夹。
 *
 * - 如果 reveal=True，将在文件管理器中显示并选中该路径
 * - 如果 reveal=False，将直接打开文件（使用系统默认程序）
 */
export const openPathOptions = (options: Options<OpenPathData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await openPath({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: openPathQueryKey(options)
    });
};

/**
 * 打开文件或文件夹
 * 在系统文件管理器中打开文件或文件夹。
 *
 * - 如果 reveal=True，将在文件管理器中显示并选中该路径
 * - 如果 reveal=False，将直接打开文件（使用系统默认程序）
 */
export const openPathMutation = (options?: Partial<Options<OpenPathData>>): UseMutationOptions<unknown, AxiosError<OpenPathError>, Options<OpenPathData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<OpenPathError>, Options<OpenPathData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await openPath({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readNfoQueryKey = (options: Options<ReadNfoData>) => createQueryKey('readNfo', options);

/**
 * 读取 NFO 文件
 * 读取 NFO 文件的内容。
 */
export const readNfoOptions = (options: Options<ReadNfoData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await readNfo({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: readNfoQueryKey(options)
    });
};

export const saveNfoQueryKey = (options: Options<SaveNfoData>) => createQueryKey('saveNfo', options);

/**
 * 保存 NFO 文件
 * 保存 NFO 文件的内容。
 */
export const saveNfoOptions = (options: Options<SaveNfoData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await saveNfo({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: saveNfoQueryKey(options)
    });
};

/**
 * 保存 NFO 文件
 * 保存 NFO 文件的内容。
 */
export const saveNfoMutation = (options?: Partial<Options<SaveNfoData>>): UseMutationOptions<unknown, AxiosError<SaveNfoError>, Options<SaveNfoData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<SaveNfoError>, Options<SaveNfoData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await saveNfo({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const startScrapeQueryKey = (options?: Options<StartScrapeData>) => createQueryKey('startScrape', options);

/**
 * 开始刮削
 * 使用当前配置运行刮削流程, 无需额外参数
 */
export const startScrapeOptions = (options?: Options<StartScrapeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await startScrape({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: startScrapeQueryKey(options)
    });
};

/**
 * 开始刮削
 * 使用当前配置运行刮削流程, 无需额外参数
 */
export const startScrapeMutation = (options?: Partial<Options<StartScrapeData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<StartScrapeData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<StartScrapeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await startScrape({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const scrapeSingleFileQueryKey = (options: Options<ScrapeSingleFileData>) => createQueryKey('scrapeSingleFile', options);

/**
 * 单文件刮削
 */
export const scrapeSingleFileOptions = (options: Options<ScrapeSingleFileData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await scrapeSingleFile({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: scrapeSingleFileQueryKey(options)
    });
};

/**
 * 单文件刮削
 */
export const scrapeSingleFileMutation = (options?: Partial<Options<ScrapeSingleFileData>>): UseMutationOptions<unknown, AxiosError<ScrapeSingleFileError>, Options<ScrapeSingleFileData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<ScrapeSingleFileError>, Options<ScrapeSingleFileData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await scrapeSingleFile({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createSymlinkQueryKey = (options: Options<CreateSymlinkData>) => createQueryKey('createSymlink', options);

/**
 * 创建软链接
 */
export const createSymlinkOptions = (options: Options<CreateSymlinkData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createSymlink({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createSymlinkQueryKey(options)
    });
};

/**
 * 创建软链接
 */
export const createSymlinkMutation = (options?: Partial<Options<CreateSymlinkData>>): UseMutationOptions<unknown, AxiosError<CreateSymlinkError>, Options<CreateSymlinkData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<CreateSymlinkError>, Options<CreateSymlinkData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createSymlink({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const addSubtitlesQueryKey = (options?: Options<AddSubtitlesData>) => createQueryKey('addSubtitles', options);

/**
 * 检查并添加字幕
 * 检查媒体库字幕情况并自动添加 (依据本地字幕包)
 */
export const addSubtitlesOptions = (options?: Options<AddSubtitlesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await addSubtitles({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: addSubtitlesQueryKey(options)
    });
};

/**
 * 检查并添加字幕
 * 检查媒体库字幕情况并自动添加 (依据本地字幕包)
 */
export const addSubtitlesMutation = (options?: Partial<Options<AddSubtitlesData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AddSubtitlesData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AddSubtitlesData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await addSubtitles({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getActorsQueryKey = (options?: Options<GetActorsData>) => createQueryKey('getActors', options);

/**
 * 查看媒体服务器演员名单
 * 查看 emby/jellyfin 中符合条件的演员名单
 */
export const getActorsOptions = (options?: Options<GetActorsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getActors({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getActorsQueryKey(options)
    });
};

export const completeActorsQueryKey = (options?: Options<CompleteActorsData>) => createQueryKey('completeActors', options);

/**
 * 补全演员信息
 * 补全 emby/jellyfin 演员信息/头像
 */
export const completeActorsOptions = (options?: Options<CompleteActorsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await completeActors({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: completeActorsQueryKey(options)
    });
};

/**
 * 补全演员信息
 * 补全 emby/jellyfin 演员信息/头像
 */
export const completeActorsMutation = (options?: Partial<Options<CompleteActorsData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CompleteActorsData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CompleteActorsData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await completeActors({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const checkCookiesQueryKey = (options?: Options<CheckCookiesData>) => createQueryKey('checkCookies', options);

/**
 * Cookie 有效性检查
 */
export const checkCookiesOptions = (options?: Options<CheckCookiesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await checkCookies({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: checkCookiesQueryKey(options)
    });
};

/**
 * Cookie 有效性检查
 */
export const checkCookiesMutation = (options?: Partial<Options<CheckCookiesData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CheckCookiesData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CheckCookiesData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await checkCookies({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSiteUrlsQueryKey = (options?: Options<GetSiteUrlsData>) => createQueryKey('getSiteUrls', options);

/**
 * 获取网站自定义网址
 * 获取网站自定义网址设置.
 */
export const getSiteUrlsOptions = (options?: Options<GetSiteUrlsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSiteUrls({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSiteUrlsQueryKey(options)
    });
};

export const setSiteUrlQueryKey = (options: Options<SetSiteUrlData>) => createQueryKey('setSiteUrl', options);

/**
 * 设置网站自定义网址
 * 指定网站自定义网址设置
 */
export const setSiteUrlOptions = (options: Options<SetSiteUrlData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await setSiteUrl({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: setSiteUrlQueryKey(options)
    });
};

/**
 * 设置网站自定义网址
 * 指定网站自定义网址设置
 */
export const setSiteUrlMutation = (options?: Partial<Options<SetSiteUrlData>>): UseMutationOptions<unknown, AxiosError<SetSiteUrlError>, Options<SetSiteUrlData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<SetSiteUrlError>, Options<SetSiteUrlData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await setSiteUrl({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const startScrape2QueryKey = (options?: Options<StartScrape2Data>) => createQueryKey('startScrape2', options);

/**
 * 开始刮削
 * 启动刮削任务
 *
 * - default 模式: 刮削配置的媒体目录
 * - single 模式: 刮削单个文件，需要提供 path 和可选的 url
 */
export const startScrape2Options = (options?: Options<StartScrape2Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await startScrape2({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: startScrape2QueryKey(options)
    });
};

/**
 * 开始刮削
 * 启动刮削任务
 *
 * - default 模式: 刮削配置的媒体目录
 * - single 模式: 刮削单个文件，需要提供 path 和可选的 url
 */
export const startScrape2Mutation = (options?: Partial<Options<StartScrape2Data>>): UseMutationOptions<StartScrape2Response, AxiosError<StartScrape2Error>, Options<StartScrape2Data>> => {
    const mutationOptions: UseMutationOptions<StartScrape2Response, AxiosError<StartScrape2Error>, Options<StartScrape2Data>> = {
        mutationFn: async (localOptions) => {
            const { data } = await startScrape2({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const stopScrapeQueryKey = (options?: Options<StopScrapeData>) => createQueryKey('stopScrape', options);

/**
 * 停止刮削
 * 停止当前刮削任务
 *
 * 注意: 停止操作是异步的，可能需要等待正在进行的任务完成
 */
export const stopScrapeOptions = (options?: Options<StopScrapeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await stopScrape({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: stopScrapeQueryKey(options)
    });
};

/**
 * 停止刮削
 * 停止当前刮削任务
 *
 * 注意: 停止操作是异步的，可能需要等待正在进行的任务完成
 */
export const stopScrapeMutation = (options?: Partial<Options<StopScrapeData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<StopScrapeData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<StopScrapeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await stopScrape({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getScrapeStatusQueryKey = (options?: Options<GetScrapeStatusData>) => createQueryKey('getScrapeStatus', options);

/**
 * 获取刮削状态
 * 获取当前刮削任务的状态和进度
 */
export const getScrapeStatusOptions = (options?: Options<GetScrapeStatusData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getScrapeStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getScrapeStatusQueryKey(options)
    });
};

export const getScrapeResultsQueryKey = (options?: Options<GetScrapeResultsData>) => createQueryKey('getScrapeResults', options);

/**
 * 获取刮削结果
 * 获取刮削结果列表（成功和失败）
 */
export const getScrapeResultsOptions = (options?: Options<GetScrapeResultsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getScrapeResults({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getScrapeResultsQueryKey(options)
    });
};

export const checkNetworkQueryKey = (options?: Options<CheckNetworkData>) => createQueryKey('checkNetwork', options);

/**
 * 网络连通性检测
 * 检测网络连通性
 *
 * 可以指定要检测的网站列表，或检测所有预设网站
 */
export const checkNetworkOptions = (options?: Options<CheckNetworkData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await checkNetwork({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: checkNetworkQueryKey(options)
    });
};

/**
 * 网络连通性检测
 * 检测网络连通性
 *
 * 可以指定要检测的网站列表，或检测所有预设网站
 */
export const checkNetworkMutation = (options?: Partial<Options<CheckNetworkData>>): UseMutationOptions<CheckNetworkResponse, AxiosError<CheckNetworkError>, Options<CheckNetworkData>> => {
    const mutationOptions: UseMutationOptions<CheckNetworkResponse, AxiosError<CheckNetworkError>, Options<CheckNetworkData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await checkNetwork({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getProxyStatusQueryKey = (options?: Options<GetProxyStatusData>) => createQueryKey('getProxyStatus', options);

/**
 * 获取代理状态
 * 获取当前代理配置状态
 */
export const getProxyStatusOptions = (options?: Options<GetProxyStatusData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getProxyStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getProxyStatusQueryKey(options)
    });
};

export const cropImageQueryKey = (options: Options<CropImageData>) => createQueryKey('cropImage', options);

/**
 * 图片裁剪
 * 裁剪图片
 *
 * 支持指定裁剪框坐标和可选的水印添加
 */
export const cropImageOptions = (options: Options<CropImageData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await cropImage({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: cropImageQueryKey(options)
    });
};

/**
 * 图片裁剪
 * 裁剪图片
 *
 * 支持指定裁剪框坐标和可选的水印添加
 */
export const cropImageMutation = (options?: Partial<Options<CropImageData>>): UseMutationOptions<CropImageResponse, AxiosError<CropImageError>, Options<CropImageData>> => {
    const mutationOptions: UseMutationOptions<CropImageResponse, AxiosError<CropImageError>, Options<CropImageData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await cropImage({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const previewImageQueryKey = (options: Options<PreviewImageData>) => createQueryKey('previewImage', options);

/**
 * 图片预览
 * 预览图片
 *
 * 可选指定宽度或高度进行缩放
 */
export const previewImageOptions = (options: Options<PreviewImageData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await previewImage({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: previewImageQueryKey(options)
    });
};

export const addWatermarkQueryKey = (options: Options<AddWatermarkData>) => createQueryKey('addWatermark', options);

/**
 * 添加水印
 * 为图片添加水印
 *
 * 支持同时添加多个水印
 */
export const addWatermarkOptions = (options: Options<AddWatermarkData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await addWatermark({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: addWatermarkQueryKey(options)
    });
};

/**
 * 添加水印
 * 为图片添加水印
 *
 * 支持同时添加多个水印
 */
export const addWatermarkMutation = (options?: Partial<Options<AddWatermarkData>>): UseMutationOptions<unknown, AxiosError<AddWatermarkError>, Options<AddWatermarkData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<AddWatermarkError>, Options<AddWatermarkData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await addWatermark({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getImageInfoQueryKey = (options: Options<GetImageInfoData>) => createQueryKey('getImageInfo', options);

/**
 * 获取图片信息
 * 获取图片的基本信息
 */
export const getImageInfoOptions = (options: Options<GetImageInfoData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getImageInfo({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getImageInfoQueryKey(options)
    });
};

export const findMissingQueryKey = (options: Options<FindMissingData>) => createQueryKey('findMissing', options);

/**
 * 查找缺失番号
 * 根据演员名字查找本地缺失的番号，结果通过 WebSocket 日志返回
 */
export const findMissingOptions = (options: Options<FindMissingData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await findMissing({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: findMissingQueryKey(options)
    });
};

/**
 * 查找缺失番号
 * 根据演员名字查找本地缺失的番号，结果通过 WebSocket 日志返回
 */
export const findMissingMutation = (options?: Partial<Options<FindMissingData>>): UseMutationOptions<unknown, AxiosError<FindMissingError>, Options<FindMissingData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<FindMissingError>, Options<FindMissingData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await findMissing({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const moveVideosQueryKey = (options: Options<MoveVideosData>) => createQueryKey('moveVideos', options);

/**
 * 移动视频和字幕
 * 移动视频和字幕文件到 Movie_moved 目录，结果通过 WebSocket 日志返回
 */
export const moveVideosOptions = (options: Options<MoveVideosData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await moveVideos({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: moveVideosQueryKey(options)
    });
};

/**
 * 移动视频和字幕
 * 移动视频和字幕文件到 Movie_moved 目录，结果通过 WebSocket 日志返回
 */
export const moveVideosMutation = (options?: Partial<Options<MoveVideosData>>): UseMutationOptions<unknown, AxiosError<MoveVideosError>, Options<MoveVideosData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<MoveVideosError>, Options<MoveVideosData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await moveVideos({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const cleanFilesQueryKey = (options?: Options<CleanFilesData>) => createQueryKey('cleanFiles', options);

/**
 * 检查并清理文件
 * 根据配置的清理规则检查并清理文件，结果通过 WebSocket 日志返回
 */
export const cleanFilesOptions = (options?: Options<CleanFilesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await cleanFiles({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: cleanFilesQueryKey(options)
    });
};

/**
 * 检查并清理文件
 * 根据配置的清理规则检查并清理文件，结果通过 WebSocket 日志返回
 */
export const cleanFilesMutation = (options?: Partial<Options<CleanFilesData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CleanFilesData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CleanFilesData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await cleanFiles({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const manageExtrasQueryKey = (options: Options<ManageExtrasData>) => createQueryKey('manageExtras', options);

/**
 * 管理 extras 附加内容
 * 添加或删除 extrafanart extras (behind the scenes 文件夹)，结果通过 WebSocket 日志返回
 */
export const manageExtrasOptions = (options: Options<ManageExtrasData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await manageExtras({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: manageExtrasQueryKey(options)
    });
};

/**
 * 管理 extras 附加内容
 * 添加或删除 extrafanart extras (behind the scenes 文件夹)，结果通过 WebSocket 日志返回
 */
export const manageExtrasMutation = (options?: Partial<Options<ManageExtrasData>>): UseMutationOptions<unknown, AxiosError<ManageExtrasError>, Options<ManageExtrasData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<ManageExtrasError>, Options<ManageExtrasData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await manageExtras({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const manageExtrafanartCopyQueryKey = (options: Options<ManageExtrafanartCopyData>) => createQueryKey('manageExtrafanartCopy', options);

/**
 * 管理剧照副本
 * 添加或删除剧照副本，结果通过 WebSocket 日志返回
 */
export const manageExtrafanartCopyOptions = (options: Options<ManageExtrafanartCopyData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await manageExtrafanartCopy({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: manageExtrafanartCopyQueryKey(options)
    });
};

/**
 * 管理剧照副本
 * 添加或删除剧照副本，结果通过 WebSocket 日志返回
 */
export const manageExtrafanartCopyMutation = (options?: Partial<Options<ManageExtrafanartCopyData>>): UseMutationOptions<unknown, AxiosError<ManageExtrafanartCopyError>, Options<ManageExtrafanartCopyData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<ManageExtrafanartCopyError>, Options<ManageExtrafanartCopyData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await manageExtrafanartCopy({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const manageThemeVideosQueryKey = (options: Options<ManageThemeVideosData>) => createQueryKey('manageThemeVideos', options);

/**
 * 管理主题视频
 * 添加或删除主题视频，结果通过 WebSocket 日志返回
 */
export const manageThemeVideosOptions = (options: Options<ManageThemeVideosData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await manageThemeVideos({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: manageThemeVideosQueryKey(options)
    });
};

/**
 * 管理主题视频
 * 添加或删除主题视频，结果通过 WebSocket 日志返回
 */
export const manageThemeVideosMutation = (options?: Partial<Options<ManageThemeVideosData>>): UseMutationOptions<unknown, AxiosError<ManageThemeVideosError>, Options<ManageThemeVideosData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<ManageThemeVideosError>, Options<ManageThemeVideosData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await manageThemeVideos({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};