// This file is auto-generated by @hey-api/openapi-ts

/**
 * CDChar
 */
export type CdChar = 'letter' | 'endc' | 'digital' | 'middle_number' | 'underline' | 'space' | 'point';

/**
 * CleanAction
 */
export type CleanAction = 'clean_ext' | 'clean_name' | 'clean_contains' | 'clean_size' | 'clean_ignore_ext' | 'clean_ignore_contains' | 'i_know' | 'i_agree' | 'auto_clean';

/**
 * 配置
 */
export type ConfigInput = {
    /**
     * 媒体路径
     */
    media_path?: string;
    /**
     * 软链接路径
     */
    softlink_path?: string;
    /**
     * 成功输出目录
     */
    success_output_folder?: string;
    /**
     * 失败输出目录
     */
    failed_output_folder?: string;
    /**
     * 额外剧照目录
     */
    extrafanart_folder?: string;
    /**
     * 媒体类型
     */
    media_type?: Array<string>;
    /**
     * 字幕类型
     */
    sub_type?: Array<string>;
    /**
     * 刮削软链接路径
     */
    scrape_softlink_path?: boolean;
    /**
     * 自动创建软链接
     */
    auto_link?: boolean;
    /**
     * 排除的目录
     */
    folders?: Array<string>;
    /**
     * 要从文件名中删除的字符串
     */
    string?: Array<string>;
    /**
     * 要处理的最小文件大小（MB）
     */
    file_size?: number;
    /**
     * 不转义的字符串
     */
    no_escape?: Array<NoEscape>;
    /**
     * 清理规则: 扩展名
     */
    clean_ext?: Array<string>;
    /**
     * 清理规则: 文件名(完全匹配)
     */
    clean_name?: Array<string>;
    /**
     * 清理规则: 文件名包含
     */
    clean_contains?: Array<string>;
    /**
     * 清理小于此大小的文件（KB）
     */
    clean_size?: number;
    /**
     * 清理规则: 排除扩展名
     */
    clean_ignore_ext?: Array<string>;
    /**
     * 清理规则: 排除文件名包含
     */
    clean_ignore_contains?: Array<string>;
    /**
     * 启用的清理规则
     */
    clean_enable?: Array<CleanAction>;
    /**
     * 并发数
     */
    thread_number?: number;
    /**
     * 线程时间
     */
    thread_time?: number;
    /**
     * Javdb时间
     */
    javdb_time?: number;
    /**
     * 主模式
     * 正常模式适合海报墙用户; 视频模式仅整理视频
     */
    main_mode?: 1 | 2;
    /**
     * 读取模式
     */
    read_mode?: Array<ReadMode>;
    /**
     * 更新模式
     */
    update_mode?: string;
    /**
     * 更新A目录
     */
    update_a_folder?: string;
    /**
     * 更新B目录
     */
    update_b_folder?: string;
    /**
     * 更新C文件模板
     */
    update_c_filetemplate?: string;
    /**
     * 更新D目录
     */
    update_d_folder?: string;
    /**
     * 更新标题模板
     */
    update_titletemplate?: string;
    /**
     * 链接模式
     * 软链接适合网盘用户; 硬链接适合PT用户
     */
    soft_link?: 0 | 1 | 2;
    /**
     * 成功后移动文件
     */
    success_file_move?: boolean;
    /**
     * 失败后移动文件
     */
    failed_file_move?: boolean;
    /**
     * 成功后重命名文件
     */
    success_file_rename?: boolean;
    /**
     * 删除空目录
     */
    del_empty_folder?: boolean;
    /**
     * 显示海报
     */
    show_poster?: boolean;
    /**
     * 下载文件类型
     */
    download_files?: Array<DownloadableFile>;
    /**
     * 保留文件类型
     */
    keep_files?: Array<KeepableFile>;
    /**
     * 高清图片来源
     */
    download_hd_pics?: Array<HdPicSource>;
    /**
     * Google使用
     */
    google_used?: Array<string>;
    /**
     * Google搜图排除的网址
     */
    google_exclude?: Array<string>;
    /**
     * 刮削模式
     */
    scrape_like?: 'info' | 'speed' | 'single';
    /**
     * 单个网站
     */
    website_single?: Website;
    /**
     * 有码网站源
     */
    website_youma?: Array<Website>;
    /**
     * 无码网站源
     */
    website_wuma?: Array<Website>;
    /**
     * 素人网站源
     */
    website_suren?: Array<Website>;
    /**
     * FC2网站源
     */
    website_fc2?: Array<Website>;
    /**
     * 欧美网站源
     */
    website_oumei?: Array<Website>;
    /**
     * 国产网站源
     */
    website_guochan?: Array<Website>;
    /**
     * 使用色花标题
     */
    title_sehua?: boolean;
    /**
     * 使用 Yesjav 标题
     */
    title_yesjav?: boolean;
    /**
     * 使用色花中文标题
     */
    title_sehua_zh?: boolean;
    /**
     * 演员真名
     */
    actor_realname?: boolean;
    /**
     * 简介格式
     */
    outline_format?: Array<OutlineShow>;
    /**
     * 字段配置
     */
    field_configs?: {
        [key in CrawlerResultFields]?: FieldConfig;
    };
    /**
     * 网站配置
     */
    site_configs?: {
        [key in Website]?: SiteConfig;
    };
    /**
     * 翻译配置
     */
    translate_config?: TranslateConfig;
    /**
     * NFO包含内容
     */
    nfo_include_new?: Array<NfoInclude>;
    /**
     * NFO标语
     */
    nfo_tagline?: string;
    /**
     * 包含标签
     */
    nfo_tag_include?: Array<TagInclude>;
    /**
     * NFO系列标签
     */
    nfo_tag_series?: string;
    /**
     * NFO工作室标签
     */
    nfo_tag_studio?: string;
    /**
     * NFO发行商标签
     */
    nfo_tag_publisher?: string;
    /**
     * NFO演员标签
     */
    nfo_tag_actor?: string;
    /**
     * NFO 演员名白名单
     */
    nfo_tag_actor_contains?: Array<string>;
    /**
     * 目录名称
     */
    folder_name?: string;
    /**
     * 文件命名
     */
    naming_file?: string;
    /**
     * 媒体命名
     */
    naming_media?: string;
    /**
     * 禁止字符
     */
    prevent_char?: string;
    /**
     * 字段规则
     */
    fields_rule?: Array<FieldRule>;
    /**
     * 后缀排序
     */
    suffix_sort?: Array<SuffixSort>;
    /**
     * 未知演员名称
     */
    actor_no_name?: string;
    /**
     * 发布规则
     */
    release_rule?: string;
    /**
     * 目录名称最大长度
     */
    folder_name_max?: number;
    /**
     * 文件名称最大长度
     */
    file_name_max?: number;
    /**
     * 演员名称最大数量
     */
    actor_name_max?: number;
    /**
     * 更多演员名称
     */
    actor_name_more?: string;
    /**
     * UMR样式
     */
    umr_style?: string;
    /**
     * 泄露样式
     */
    leak_style?: string;
    /**
     * 无码样式
     */
    wuma_style?: string;
    /**
     * 有码样式
     */
    youma_style?: string;
    /**
     * CD名称
     */
    cd_name?: number;
    /**
     * 分集规则
     */
    cd_char?: Array<CdChar>;
    /**
     * 图片简化命名
     */
    pic_simple_name?: boolean;
    /**
     * 预告片简化命名
     */
    trailer_simple_name?: boolean;
    /**
     * 高清名称
     */
    hd_name?: 'height' | 'hd';
    /**
     * 获取高清
     */
    hd_get?: 'video' | 'path' | 'none';
    /**
     * 中文字符
     */
    cnword_char?: Array<string>;
    /**
     * 中文样式
     */
    cnword_style?: string;
    /**
     * 目录中文
     */
    folder_cnword?: boolean;
    /**
     * 文件中文
     */
    file_cnword?: boolean;
    /**
     * 字幕目录
     */
    subtitle_folder?: string;
    /**
     * 添加字幕
     */
    subtitle_add?: boolean;
    /**
     * 添加中文字幕
     */
    subtitle_add_chs?: boolean;
    /**
     * 重新刮削时添加字幕
     */
    subtitle_add_rescrape?: boolean;
    /**
     * 服务器类型
     */
    server_type?: 'emby' | 'jellyfin';
    /**
     * Emby网址
     */
    emby_url?: string;
    /**
     * API密钥
     */
    api_key?: string;
    /**
     * 用户ID
     */
    user_id?: string;
    /**
     * Emby功能开关
     */
    emby_on?: Array<EmbyAction>;
    /**
     * 使用数据库
     */
    use_database?: boolean;
    /**
     * 信息数据库路径
     */
    info_database_path?: string;
    /**
     * Gfriends Github
     */
    gfriends_github?: string;
    /**
     * 演员照片目录
     */
    actor_photo_folder?: string;
    /**
     * 演员照片Kodi自动
     */
    actor_photo_kodi_auto?: boolean;
    /**
     * 海报水印
     * 是否在海报图片上添加水印
     */
    poster_mark?: 0 | 1;
    /**
     * 缩略图水印
     * 是否在缩略图上添加水印
     */
    thumb_mark?: 0 | 1;
    /**
     * 背景图水印
     * 是否在背景图上添加水印
     */
    fanart_mark?: 0 | 1;
    /**
     * 水印大小
     */
    mark_size?: number;
    /**
     * 水印类型
     */
    mark_type?: Array<MarkType>;
    /**
     * 水印添加规则
     * not_fixed: 不固定位置. 将从首个位置开始顺时针方向依次添加; fixed: 固定一个位置, 水印在此依次横向添加; corner: 分别设置不同种类水印的位置.
     */
    mark_fixed?: 'not_fixed' | 'fixed' | 'corner';
    /**
     * 水印规则为不固定时首个水印的位置
     */
    mark_pos?: string;
    /**
     * 水印规则为固定时的位置
     */
    mark_pos_corner?: string;
    /**
     * 中文字幕水印位置
     */
    mark_pos_sub?: string;
    /**
     * 马赛克类型水印位置
     */
    mark_pos_mosaic?: string;
    /**
     * 清晰度水印位置
     */
    mark_pos_hd?: string;
    /**
     * 代理类型
     */
    use_proxy?: boolean;
    /**
     * 代理地址
     */
    proxy?: string;
    /**
     * 超时
     */
    timeout?: number;
    /**
     * 重试
     */
    retry?: number;
    /**
     * Theporndb API令牌
     */
    theporndb_api_token?: string;
    /**
     * Javdb
     */
    javdb?: string;
    /**
     * Javbus
     */
    javbus?: string;
    /**
     * 显示网页日志
     */
    show_web_log?: boolean;
    /**
     * 显示来源日志
     */
    show_from_log?: boolean;
    /**
     * 显示数据日志
     */
    show_data_log?: boolean;
    /**
     * 保存日志
     */
    save_log?: boolean;
    /**
     * 检查更新
     */
    update_check?: boolean;
    /**
     * 本地库
     */
    local_library?: Array<string>;
    /**
     * 演员名称
     */
    actors_name?: string;
    /**
     * 网盘路径
     */
    netdisk_path?: string;
    /**
     * 本地磁盘路径
     */
    localdisk_path?: string;
    /**
     * 窗口标题
     */
    window_title?: string;
    /**
     * 功能开关
     */
    switch_on?: Array<Switch>;
    /**
     * 定时器间隔
     */
    timed_interval?: string;
    /**
     * 休息计数
     */
    rest_count?: number;
    /**
     * 休息时间
     */
    rest_time?: string;
};

/**
 * 配置
 */
export type ConfigOutput = {
    /**
     * 媒体路径
     */
    media_path?: string;
    /**
     * 软链接路径
     */
    softlink_path?: string;
    /**
     * 成功输出目录
     */
    success_output_folder?: string;
    /**
     * 失败输出目录
     */
    failed_output_folder?: string;
    /**
     * 额外剧照目录
     */
    extrafanart_folder?: string;
    /**
     * 媒体类型
     */
    media_type?: Array<string>;
    /**
     * 字幕类型
     */
    sub_type?: Array<string>;
    /**
     * 刮削软链接路径
     */
    scrape_softlink_path?: boolean;
    /**
     * 自动创建软链接
     */
    auto_link?: boolean;
    /**
     * 排除的目录
     */
    folders?: Array<string>;
    /**
     * 要从文件名中删除的字符串
     */
    string?: Array<string>;
    /**
     * 要处理的最小文件大小（MB）
     */
    file_size?: number;
    /**
     * 不转义的字符串
     */
    no_escape?: Array<NoEscape>;
    /**
     * 清理规则: 扩展名
     */
    clean_ext?: Array<string>;
    /**
     * 清理规则: 文件名(完全匹配)
     */
    clean_name?: Array<string>;
    /**
     * 清理规则: 文件名包含
     */
    clean_contains?: Array<string>;
    /**
     * 清理小于此大小的文件（KB）
     */
    clean_size?: number;
    /**
     * 清理规则: 排除扩展名
     */
    clean_ignore_ext?: Array<string>;
    /**
     * 清理规则: 排除文件名包含
     */
    clean_ignore_contains?: Array<string>;
    /**
     * 启用的清理规则
     */
    clean_enable?: Array<CleanAction>;
    /**
     * 并发数
     */
    thread_number?: number;
    /**
     * 线程时间
     */
    thread_time?: number;
    /**
     * Javdb时间
     */
    javdb_time?: number;
    /**
     * 主模式
     * 正常模式适合海报墙用户; 视频模式仅整理视频
     */
    main_mode?: 1 | 2;
    /**
     * 读取模式
     */
    read_mode?: Array<ReadMode>;
    /**
     * 更新模式
     */
    update_mode?: string;
    /**
     * 更新A目录
     */
    update_a_folder?: string;
    /**
     * 更新B目录
     */
    update_b_folder?: string;
    /**
     * 更新C文件模板
     */
    update_c_filetemplate?: string;
    /**
     * 更新D目录
     */
    update_d_folder?: string;
    /**
     * 更新标题模板
     */
    update_titletemplate?: string;
    /**
     * 链接模式
     * 软链接适合网盘用户; 硬链接适合PT用户
     */
    soft_link?: 0 | 1 | 2;
    /**
     * 成功后移动文件
     */
    success_file_move?: boolean;
    /**
     * 失败后移动文件
     */
    failed_file_move?: boolean;
    /**
     * 成功后重命名文件
     */
    success_file_rename?: boolean;
    /**
     * 删除空目录
     */
    del_empty_folder?: boolean;
    /**
     * 显示海报
     */
    show_poster?: boolean;
    /**
     * 下载文件类型
     */
    download_files?: Array<DownloadableFile>;
    /**
     * 保留文件类型
     */
    keep_files?: Array<KeepableFile>;
    /**
     * 高清图片来源
     */
    download_hd_pics?: Array<HdPicSource>;
    /**
     * Google使用
     */
    google_used?: Array<string>;
    /**
     * Google搜图排除的网址
     */
    google_exclude?: Array<string>;
    /**
     * 刮削模式
     */
    scrape_like?: 'info' | 'speed' | 'single';
    /**
     * 单个网站
     */
    website_single?: Website;
    /**
     * 有码网站源
     */
    website_youma?: Array<Website>;
    /**
     * 无码网站源
     */
    website_wuma?: Array<Website>;
    /**
     * 素人网站源
     */
    website_suren?: Array<Website>;
    /**
     * FC2网站源
     */
    website_fc2?: Array<Website>;
    /**
     * 欧美网站源
     */
    website_oumei?: Array<Website>;
    /**
     * 国产网站源
     */
    website_guochan?: Array<Website>;
    /**
     * 使用色花标题
     */
    title_sehua?: boolean;
    /**
     * 使用 Yesjav 标题
     */
    title_yesjav?: boolean;
    /**
     * 使用色花中文标题
     */
    title_sehua_zh?: boolean;
    /**
     * 演员真名
     */
    actor_realname?: boolean;
    /**
     * 简介格式
     */
    outline_format?: Array<OutlineShow>;
    /**
     * 字段配置
     */
    field_configs?: {
        [key in CrawlerResultFields]?: FieldConfig;
    };
    /**
     * 网站配置
     */
    site_configs?: {
        [key in Website]?: SiteConfig;
    };
    /**
     * 翻译配置
     */
    translate_config?: TranslateConfig;
    /**
     * NFO包含内容
     */
    nfo_include_new?: Array<NfoInclude>;
    /**
     * NFO标语
     */
    nfo_tagline?: string;
    /**
     * 包含标签
     */
    nfo_tag_include?: Array<TagInclude>;
    /**
     * NFO系列标签
     */
    nfo_tag_series?: string;
    /**
     * NFO工作室标签
     */
    nfo_tag_studio?: string;
    /**
     * NFO发行商标签
     */
    nfo_tag_publisher?: string;
    /**
     * NFO演员标签
     */
    nfo_tag_actor?: string;
    /**
     * NFO 演员名白名单
     */
    nfo_tag_actor_contains?: Array<string>;
    /**
     * 目录名称
     */
    folder_name?: string;
    /**
     * 文件命名
     */
    naming_file?: string;
    /**
     * 媒体命名
     */
    naming_media?: string;
    /**
     * 禁止字符
     */
    prevent_char?: string;
    /**
     * 字段规则
     */
    fields_rule?: Array<FieldRule>;
    /**
     * 后缀排序
     */
    suffix_sort?: Array<SuffixSort>;
    /**
     * 未知演员名称
     */
    actor_no_name?: string;
    /**
     * 发布规则
     */
    release_rule?: string;
    /**
     * 目录名称最大长度
     */
    folder_name_max?: number;
    /**
     * 文件名称最大长度
     */
    file_name_max?: number;
    /**
     * 演员名称最大数量
     */
    actor_name_max?: number;
    /**
     * 更多演员名称
     */
    actor_name_more?: string;
    /**
     * UMR样式
     */
    umr_style?: string;
    /**
     * 泄露样式
     */
    leak_style?: string;
    /**
     * 无码样式
     */
    wuma_style?: string;
    /**
     * 有码样式
     */
    youma_style?: string;
    /**
     * CD名称
     */
    cd_name?: number;
    /**
     * 分集规则
     */
    cd_char?: Array<CdChar>;
    /**
     * 图片简化命名
     */
    pic_simple_name?: boolean;
    /**
     * 预告片简化命名
     */
    trailer_simple_name?: boolean;
    /**
     * 高清名称
     */
    hd_name?: 'height' | 'hd';
    /**
     * 获取高清
     */
    hd_get?: 'video' | 'path' | 'none';
    /**
     * 中文字符
     */
    cnword_char?: Array<string>;
    /**
     * 中文样式
     */
    cnword_style?: string;
    /**
     * 目录中文
     */
    folder_cnword?: boolean;
    /**
     * 文件中文
     */
    file_cnword?: boolean;
    /**
     * 字幕目录
     */
    subtitle_folder?: string;
    /**
     * 添加字幕
     */
    subtitle_add?: boolean;
    /**
     * 添加中文字幕
     */
    subtitle_add_chs?: boolean;
    /**
     * 重新刮削时添加字幕
     */
    subtitle_add_rescrape?: boolean;
    /**
     * 服务器类型
     */
    server_type?: 'emby' | 'jellyfin';
    /**
     * Emby网址
     */
    emby_url?: string;
    /**
     * API密钥
     */
    api_key?: string;
    /**
     * 用户ID
     */
    user_id?: string;
    /**
     * Emby功能开关
     */
    emby_on?: Array<EmbyAction>;
    /**
     * 使用数据库
     */
    use_database?: boolean;
    /**
     * 信息数据库路径
     */
    info_database_path?: string;
    /**
     * Gfriends Github
     */
    gfriends_github?: string;
    /**
     * 演员照片目录
     */
    actor_photo_folder?: string;
    /**
     * 演员照片Kodi自动
     */
    actor_photo_kodi_auto?: boolean;
    /**
     * 海报水印
     * 是否在海报图片上添加水印
     */
    poster_mark?: 0 | 1;
    /**
     * 缩略图水印
     * 是否在缩略图上添加水印
     */
    thumb_mark?: 0 | 1;
    /**
     * 背景图水印
     * 是否在背景图上添加水印
     */
    fanart_mark?: 0 | 1;
    /**
     * 水印大小
     */
    mark_size?: number;
    /**
     * 水印类型
     */
    mark_type?: Array<MarkType>;
    /**
     * 水印添加规则
     * not_fixed: 不固定位置. 将从首个位置开始顺时针方向依次添加; fixed: 固定一个位置, 水印在此依次横向添加; corner: 分别设置不同种类水印的位置.
     */
    mark_fixed?: 'not_fixed' | 'fixed' | 'corner';
    /**
     * 水印规则为不固定时首个水印的位置
     */
    mark_pos?: string;
    /**
     * 水印规则为固定时的位置
     */
    mark_pos_corner?: string;
    /**
     * 中文字幕水印位置
     */
    mark_pos_sub?: string;
    /**
     * 马赛克类型水印位置
     */
    mark_pos_mosaic?: string;
    /**
     * 清晰度水印位置
     */
    mark_pos_hd?: string;
    /**
     * 代理类型
     */
    use_proxy?: boolean;
    /**
     * 代理地址
     */
    proxy?: string;
    /**
     * 超时
     */
    timeout?: number;
    /**
     * 重试
     */
    retry?: number;
    /**
     * Theporndb API令牌
     */
    theporndb_api_token?: string;
    /**
     * Javdb
     */
    javdb?: string;
    /**
     * Javbus
     */
    javbus?: string;
    /**
     * 显示网页日志
     */
    show_web_log?: boolean;
    /**
     * 显示来源日志
     */
    show_from_log?: boolean;
    /**
     * 显示数据日志
     */
    show_data_log?: boolean;
    /**
     * 保存日志
     */
    save_log?: boolean;
    /**
     * 检查更新
     */
    update_check?: boolean;
    /**
     * 本地库
     */
    local_library?: Array<string>;
    /**
     * 演员名称
     */
    actors_name?: string;
    /**
     * 网盘路径
     */
    netdisk_path?: string;
    /**
     * 本地磁盘路径
     */
    localdisk_path?: string;
    /**
     * 窗口标题
     */
    window_title?: string;
    /**
     * 功能开关
     */
    switch_on?: Array<Switch>;
    /**
     * 定时器间隔
     */
    timed_interval?: string;
    /**
     * 休息计数
     */
    rest_count?: number;
    /**
     * 休息时间
     */
    rest_time?: string;
};

/**
 * ConfigSwitchResponse
 */
export type ConfigSwitchResponse = {
    config: ConfigOutput;
    /**
     * Errors
     * 加载配置时发生的错误信息列表
     */
    errors: Array<string>;
};

/**
 * CrawlerResultFields
 */
export type CrawlerResultFields = 'number' | 'mosaic' | 'image_download' | 'actors' | 'all_actors' | 'directors' | 'extrafanart' | 'originalplot' | 'originaltitle' | 'outline' | 'poster' | 'publisher' | 'release' | 'runtime' | 'score' | 'series' | 'studio' | 'tags' | 'thumb' | 'title' | 'trailer' | 'wanted' | 'year' | 'image_cut' | 'source' | 'external_id';

/**
 * CreateSoftlinksBody
 */
export type CreateSoftlinksBody = {
    /**
     * Source Dir
     * 待软链接的源目录
     */
    source_dir: string;
    /**
     * Dest Dir
     * 创建软链接的目标目录
     */
    dest_dir: string;
    /**
     * Copy Files
     * 是否复制 nfo, 图片, 字幕等文件
     */
    copy_files?: boolean;
};

/**
 * CropBox
 * 裁剪框
 */
export type CropBox = {
    /**
     * X1
     * 左上角 X 坐标
     */
    x1: number;
    /**
     * Y1
     * 左上角 Y 坐标
     */
    y1: number;
    /**
     * X2
     * 右下角 X 坐标
     */
    x2: number;
    /**
     * Y2
     * 右下角 Y 坐标
     */
    y2: number;
};

/**
 * CropRequest
 * 图片裁剪请求
 */
export type CropRequest = {
    /**
     * Source Path
     * 源图片路径
     */
    source_path: string;
    /**
     * 裁剪框坐标
     */
    crop_box: CropBox;
    /**
     * 水印选项
     */
    watermark?: WatermarkOptions | null;
    /**
     * Output Path
     * 输出路径，为空则覆盖源文件
     */
    output_path?: string | null;
    /**
     * Quality
     * 输出质量 (1-100)
     */
    quality?: number;
};

/**
 * CropResponse
 * 图片裁剪响应
 */
export type CropResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Path
     */
    path: string;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
};

/**
 * DownloadableFile
 */
export type DownloadableFile = 'poster' | 'thumb' | 'fanart' | 'extrafanart' | 'trailer' | 'nfo' | 'extrafanart_extras' | 'extrafanart_copy' | 'theme_videos' | 'ignore_pic_fail' | 'ignore_youma' | 'ignore_wuma' | 'ignore_fc2' | 'ignore_guochan' | 'ignore_size';

/**
 * EmbyAction
 */
export type EmbyAction = 'actor_info_zh_cn' | 'actor_info_zh_tw' | 'actor_info_ja' | 'actor_info_all' | 'actor_info_miss' | 'actor_photo_net' | 'actor_photo_local' | 'actor_photo_all' | 'actor_photo_miss' | 'actor_info_translate' | 'actor_info_photo' | 'graphis_backdrop' | 'graphis_face' | 'graphis_new' | 'actor_photo_auto' | 'actor_replace';

/**
 * ExtrasBody
 */
export type ExtrasBody = {
    /**
     * Mode
     * 操作模式: add=添加, del=删除
     */
    mode: 'add' | 'del';
};

/**
 * 字段设置
 */
export type FieldConfig = {
    /**
     * 来源网站优先级
     */
    site_prority?: Array<Website>;
    /**
     * 语言偏好
     */
    language?: Language;
    /**
     * 翻译此字段
     * 若启用则使用首个来源的数据并翻译为指定语言; 否则使用第一个指定语言的数据, 如果所有来源都没有指定语言数据则视为失败.
     */
    translate?: boolean;
};

/**
 * FieldRule
 */
export type FieldRule = 'del_actor' | 'del_char' | 'fc2_seller' | 'del_num';

/**
 * FileItem
 * Represents a file or directory item.
 */
export type FileItem = {
    /**
     * Name
     * The name of the file or directory.
     */
    name: string;
    /**
     * Path
     * The absolute path of the file or directory.
     */
    path: string;
    /**
     * Type
     * The type of the item. 'file' or 'directory'.
     */
    type: 'file' | 'directory';
    /**
     * Size
     * The size of the file in bytes. Omitted for directories.
     */
    size?: number | null;
    /**
     * Last Modified
     */
    last_modified?: string | null;
};

/**
 * FileListResponse
 * The response structure for the file list endpoint.
 */
export type FileListResponse = {
    /**
     * Items
     * 指定路径下的文件和目录列表. 先目录后文件, 均按名称排序且不区分大小写.
     */
    items: Array<FileItem>;
    /**
     * Total
     * 路径下的文件和目录总数. 若大于 len(data) 说明 data 因文件过多被截断.
     */
    total: number;
};

/**
 * FindMissingBody
 */
export type FindMissingBody = {
    /**
     * Actors
     * 要查询的演员名字，多个用逗号分隔，也支持演员的 JAVDB 主页地址
     */
    actors: string;
    /**
     * Local Library
     * 本地媒体库路径，留空则使用配置中的路径
     */
    local_library?: Array<string>;
};

/**
 * HDPicSource
 */
export type HdPicSource = 'poster' | 'thumb' | 'amazon' | 'official' | 'google' | 'goo_only';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageInfoResponse
 * 图片信息响应
 */
export type ImageInfoResponse = {
    /**
     * Path
     */
    path: string;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
    /**
     * Format
     */
    format: string;
    /**
     * Size
     */
    size: number;
};

/**
 * KeepableFile
 */
export type KeepableFile = 'poster' | 'thumb' | 'fanart' | 'extrafanart' | 'trailer' | 'nfo' | 'extrafanart_copy' | 'theme_videos';

/**
 * Language
 */
export type Language = 'undefined' | 'unknown' | 'zh_cn' | 'zh_tw' | 'jp' | 'en';

/**
 * MarkType
 */
export type MarkType = 'sub' | 'youma' | 'umr' | 'leak' | 'uncensored' | 'hd';

/**
 * MoveVideosBody
 */
export type MoveVideosBody = {
    /**
     * Exclude Dirs
     * 排除的目录列表
     */
    exclude_dirs?: Array<string>;
};

/**
 * NetworkCheckRequest
 * 网络检测请求
 */
export type NetworkCheckRequest = {
    /**
     * Sites
     * 要检测的网站列表，为空则检测所有
     */
    sites?: Array<string> | null;
    /**
     * Include Proxy
     * 是否检测代理
     */
    include_proxy?: boolean;
};

/**
 * NetworkCheckResponse
 * 网络检测响应
 */
export type NetworkCheckResponse = {
    proxy: ProxyStatus;
    /**
     * Sites
     * 各网站检测结果
     */
    sites?: Array<SiteCheckResult>;
    /**
     * Elapsed
     * 检测用时(秒)
     */
    elapsed: number;
};

/**
 * NfoContentResponse
 * NFO 文件内容响应
 */
export type NfoContentResponse = {
    /**
     * Path
     * NFO 文件路径
     */
    path: string;
    /**
     * Content
     * NFO 文件内容（XML）
     */
    content: string;
    /**
     * Exists
     * 文件是否存在
     */
    exists: boolean;
};

/**
 * NfoInclude
 */
export type NfoInclude = 'sorttitle' | 'originaltitle' | 'title_cd' | 'outline' | 'plot_' | 'originalplot' | 'outline_no_cdata' | 'release_' | 'releasedate' | 'premiered' | 'country' | 'mpaa' | 'customrating' | 'year' | 'runtime' | 'wanted' | 'score' | 'criticrating' | 'actor' | 'actor_all' | 'director' | 'series' | 'tag' | 'genre' | 'actor_set' | 'series_set' | 'studio' | 'maker' | 'publisher' | 'label' | 'poster' | 'cover' | 'trailer' | 'website';

/**
 * NoEscape
 */
export type NoEscape = 'no_skip_small_file' | 'folder' | 'skip_success_file' | 'record_success_file' | 'check_symlink' | 'symlink_definition';

/**
 * OpenPathRequest
 * 打开路径请求
 */
export type OpenPathRequest = {
    /**
     * Path
     * 要打开的文件或文件夹路径
     */
    path: string;
    /**
     * Reveal
     * 是否在文件管理器中显示（而不是直接打开文件）
     */
    reveal?: boolean;
};

/**
 * OutlineShow
 */
export type OutlineShow = 'show_from' | 'show_zh_jp' | 'show_jp_zh';

/**
 * ProxyStatus
 * 代理状态
 */
export type ProxyStatus = {
    /**
     * Enabled
     * 是否启用代理
     */
    enabled: boolean;
    /**
     * Type
     * 代理类型
     */
    type?: string | null;
    /**
     * Host
     * 代理主机
     */
    host?: string | null;
    /**
     * Port
     * 代理端口
     */
    port?: number | null;
    /**
     * 代理状态
     */
    status?: SiteStatus;
};

/**
 * ReadMode
 */
export type ReadMode = 'has_nfo_update' | 'no_nfo_scrape' | 'read_download_again' | 'read_update_nfo';

/**
 * SaveNfoRequest
 * 保存 NFO 文件请求
 */
export type SaveNfoRequest = {
    /**
     * Path
     * NFO 文件路径
     */
    path: string;
    /**
     * Content
     * NFO 文件内容（XML）
     */
    content: string;
};

/**
 * ScrapeFileBody
 */
export type ScrapeFileBody = {
    /**
     * Path
     */
    path: string;
    /**
     * Url
     */
    url: string;
};

/**
 * ScrapeResultItem
 * 刮削结果项
 */
export type ScrapeResultItem = {
    /**
     * Path
     * 文件路径
     */
    path: string;
    /**
     * Number
     * 番号
     */
    number?: string | null;
    /**
     * Error
     * 错误信息
     */
    error?: string | null;
};

/**
 * ScrapeResultsResponse
 * 刮削结果响应
 */
export type ScrapeResultsResponse = {
    /**
     * Success
     * 成功列表
     */
    success?: Array<ScrapeResultItem>;
    /**
     * Failed
     * 失败列表
     */
    failed?: Array<ScrapeResultItem>;
};

/**
 * ScrapeStatus
 * 刮削状态枚举
 */
export type ScrapeStatus = 'idle' | 'scraping' | 'stopping';

/**
 * ScrapeStatusResponse
 * 刮削状态响应
 */
export type ScrapeStatusResponse = {
    /**
     * 当前刮削状态
     */
    status: ScrapeStatus;
    /**
     * Current
     * 当前已处理数量
     */
    current: number;
    /**
     * Total
     * 总数量
     */
    total: number;
    /**
     * Success
     * 成功数量
     */
    success: number;
    /**
     * Failed
     * 失败数量
     */
    failed: number;
    /**
     * Progress
     * 进度百分比 (0-100)
     */
    progress: number;
};

/**
 * SetSiteUrlBody
 */
export type SetSiteUrlBody = {
    site: Website;
    /**
     * Url
     */
    url: string;
};

/**
 * SiteCheckResult
 * 单个网站检测结果
 */
export type SiteCheckResult = {
    /**
     * Name
     * 网站名称
     */
    name: string;
    /**
     * Url
     * 网站 URL
     */
    url: string;
    /**
     * 连接状态
     */
    status: SiteStatus;
    /**
     * Message
     * 状态消息
     */
    message?: string;
    /**
     * Latency
     * 延迟(ms)
     */
    latency?: number | null;
};

/**
 * 网站设置
 */
export type SiteConfig = {
    /**
     * 使用无头浏览器
     */
    use_browser?: boolean;
    /**
     * 自定义网址
     */
    custom_url?: string | null;
};

/**
 * SiteStatus
 * 网站状态
 */
export type SiteStatus = 'ok' | 'error' | 'checking';

/**
 * StartScrapeRequest
 * 启动刮削请求
 */
export type StartScrapeRequest = {
    /**
     * Mode
     * 刮削模式
     */
    mode?: 'default' | 'single';
    /**
     * Path
     * 单文件刮削时的文件路径
     */
    path?: string | null;
    /**
     * Url
     * 单文件刮削时的指定 URL
     */
    url?: string | null;
};

/**
 * StartScrapeResponse
 * 启动刮削响应
 */
export type StartScrapeResponse = {
    /**
     * Message
     */
    message: string;
    status: ScrapeStatus;
};

/**
 * SuffixSort
 */
export type SuffixSort = 'moword' | 'cnword' | 'definition';

/**
 * Switch
 */
export type Switch = 'auto_start' | 'auto_exit' | 'rest_scrape' | 'timed_scrape' | 'remain_task' | 'show_dialog_exit' | 'show_dialog_stop_scrape' | 'sort_del' | 'qt_dialog' | 'theporndb_no_hash' | 'hide_dock' | 'passthrough' | 'hide_menu' | 'dark_mode' | 'copy_netdisk_nfo' | 'show_logs' | 'hide_close' | 'hide_mini' | 'hide_none' | 'ipv4_only';

/**
 * TagInclude
 */
export type TagInclude = 'actor' | 'letters' | 'series' | 'studio' | 'publisher' | 'cnword' | 'mosaic' | 'definition';

/**
 * 翻译设置
 */
export type TranslateConfig = {
    /**
     * 翻译服务
     */
    translate_by?: Array<Translator>;
    /**
     * Deepl密钥
     */
    deepl_key?: string;
    /**
     * LLM API Host
     */
    llm_url?: string;
    /**
     * 模型 ID
     */
    llm_model?: string;
    /**
     * LLM API Key
     */
    llm_key?: string;
    /**
     * LLM 提示词
     */
    llm_prompt?: string;
    /**
     * LLM 读取超时 (秒)
     * LLM 生成耗时较长, 建议设置较大值
     */
    llm_read_timeout?: number;
    /**
     * LLM 每秒最大请求数
     */
    llm_max_req_sec?: number;
    /**
     * LLM 最大尝试次数
     */
    llm_max_try?: number;
    /**
     * LLM 温度
     */
    llm_temperature?: number;
};

/**
 * Translator
 */
export type Translator = 'youdao' | 'google' | 'deepl' | 'llm';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WatermarkOptions
 * 水印选项
 */
export type WatermarkOptions = {
    /**
     * Type
     * 水印类型
     */
    type: 'sub' | '4k' | '8k' | 'youma' | 'umr' | 'leak' | 'wuma';
    /**
     * Position
     * 水印位置
     */
    position?: 'top_left' | 'top_right' | 'bottom_left' | 'bottom_right';
};

/**
 * WatermarkRequest
 * 添加水印请求
 */
export type WatermarkRequest = {
    /**
     * Source Path
     * 源图片路径
     */
    source_path: string;
    /**
     * Marks
     * 水印类型列表
     */
    marks: Array<'sub' | '4k' | '8k' | 'youma' | 'umr' | 'leak' | 'wuma'>;
    /**
     * Output Path
     * 输出路径，为空则覆盖源文件
     */
    output_path?: string | null;
};

/**
 * Website
 */
export type Website = 'airav' | 'airav_cc' | 'avsex' | 'avsox' | 'cableav' | 'cnmdb' | 'dmm' | 'faleno' | 'fantastica' | 'fc2' | 'fc2club' | 'fc2hub' | 'fc2ppvdb' | 'freejavbt' | 'getchu' | 'giga' | 'hdouban' | 'hscangku' | 'iqqtv' | 'jav321' | 'javbus' | 'javday' | 'javdb' | 'javlibrary' | 'kin8' | 'love6' | 'lulubar' | 'madouqu' | 'mdtv' | 'mgstage' | '7mmtv' | 'mywife' | 'prestige' | 'theporndb' | 'xcity' | 'dahlia' | 'getchu_dmm' | 'official';

export type DeleteConfigData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         * 待删除的配置文件名 (不含扩展名)
         */
        name: string;
    };
    url: '/api/v1/config/';
};

export type DeleteConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConfigError = DeleteConfigErrors[keyof DeleteConfigErrors];

export type DeleteConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config/';
};

export type GetCurrentConfigResponses = {
    /**
     * Successful Response
     */
    200: ConfigOutput;
};

export type GetCurrentConfigResponse = GetCurrentConfigResponses[keyof GetCurrentConfigResponses];

export type UpdateConfigData = {
    body: ConfigInput;
    path?: never;
    query?: never;
    url: '/api/v1/config/';
};

export type UpdateConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConfigError = UpdateConfigErrors[keyof UpdateConfigErrors];

export type UpdateConfigResponses = {
    /**
     * Successful Response
     */
    200: ConfigOutput;
};

export type UpdateConfigResponse = UpdateConfigResponses[keyof UpdateConfigResponses];

export type ResetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config/reset';
};

export type ResetConfigResponses = {
    /**
     * Successful Response
     */
    200: ConfigOutput;
};

export type ResetConfigResponse = ResetConfigResponses[keyof ResetConfigResponses];

export type CreateConfigData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         * 配置文件名 (不含扩展名)
         */
        name: string;
    };
    url: '/api/v1/config/create';
};

export type CreateConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConfigError = CreateConfigErrors[keyof CreateConfigErrors];

export type CreateConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SwitchConfigData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         * 待切换的配置文件名 (不含扩展名)
         */
        name: string;
    };
    url: '/api/v1/config/switch';
};

export type SwitchConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SwitchConfigError = SwitchConfigErrors[keyof SwitchConfigErrors];

export type SwitchConfigResponses = {
    /**
     * Successful Response
     */
    200: ConfigSwitchResponse;
};

export type SwitchConfigResponse = SwitchConfigResponses[keyof SwitchConfigResponses];

export type GetConfigSchemaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config/schema';
};

export type GetConfigSchemaResponses = {
    /**
     * Response Getconfigschema
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetConfigSchemaResponse = GetConfigSchemaResponses[keyof GetConfigSchemaResponses];

export type GetConfigUiSchemaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config/ui_schema';
};

export type GetConfigUiSchemaResponses = {
    /**
     * Response Getconfiguischema
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetConfigUiSchemaResponse = GetConfigUiSchemaResponses[keyof GetConfigUiSchemaResponses];

export type GetDefaultConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config/default';
};

export type GetDefaultConfigResponses = {
    /**
     * Successful Response
     */
    200: ConfigOutput;
};

export type GetDefaultConfigResponse = GetDefaultConfigResponses[keyof GetDefaultConfigResponses];

export type GetWebSocketConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ws/connections';
};

export type GetWebSocketConnectionsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Path
         * 服务器路径. 相对路径将基于 SAFE_DIRS 中的首个路径解析.
         */
        path: string;
    };
    url: '/api/v1/files/list';
};

export type ListFilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFilesError = ListFilesErrors[keyof ListFilesErrors];

export type ListFilesResponses = {
    /**
     * Successful Response
     */
    200: FileListResponse;
};

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses];

export type OpenPathData = {
    body: OpenPathRequest;
    path?: never;
    query?: never;
    url: '/api/v1/files/open';
};

export type OpenPathErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenPathError = OpenPathErrors[keyof OpenPathErrors];

export type OpenPathResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadNfoData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Path
         * NFO 文件路径
         */
        path: string;
    };
    url: '/api/v1/files/nfo';
};

export type ReadNfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadNfoError = ReadNfoErrors[keyof ReadNfoErrors];

export type ReadNfoResponses = {
    /**
     * Successful Response
     */
    200: NfoContentResponse;
};

export type ReadNfoResponse = ReadNfoResponses[keyof ReadNfoResponses];

export type SaveNfoData = {
    body: SaveNfoRequest;
    path?: never;
    query?: never;
    url: '/api/v1/files/nfo';
};

export type SaveNfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveNfoError = SaveNfoErrors[keyof SaveNfoErrors];

export type SaveNfoResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StartScrapeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/legacy/scrape';
};

export type StartScrapeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScrapeSingleFileData = {
    body: ScrapeFileBody;
    path?: never;
    query?: never;
    url: '/api/v1/legacy/scrape/single';
};

export type ScrapeSingleFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScrapeSingleFileError = ScrapeSingleFileErrors[keyof ScrapeSingleFileErrors];

export type ScrapeSingleFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateSymlinkData = {
    body: CreateSoftlinksBody;
    path?: never;
    query?: never;
    url: '/api/v1/legacy/symlink';
};

export type CreateSymlinkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSymlinkError = CreateSymlinkErrors[keyof CreateSymlinkErrors];

export type CreateSymlinkResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddSubtitlesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/legacy/subtitles';
};

export type AddSubtitlesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetActorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/legacy/actors';
};

export type GetActorsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CompleteActorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/legacy/actors/complete';
};

export type CompleteActorsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CheckCookiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/legacy/cookies';
};

export type CheckCookiesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSiteUrlsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/legacy/sites';
};

export type GetSiteUrlsResponses = {
    /**
     * Response Getsiteurls
     * Successful Response
     */
    200: {
        [key in Website]?: string;
    };
};

export type GetSiteUrlsResponse = GetSiteUrlsResponses[keyof GetSiteUrlsResponses];

export type SetSiteUrlData = {
    body: SetSiteUrlBody;
    path?: never;
    query?: never;
    url: '/api/v1/legacy/sites';
};

export type SetSiteUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetSiteUrlError = SetSiteUrlErrors[keyof SetSiteUrlErrors];

export type SetSiteUrlResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StartScrape2Data = {
    /**
     * Body
     */
    body?: StartScrapeRequest | null;
    path?: never;
    query?: never;
    url: '/api/v1/scrape/start';
};

export type StartScrape2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartScrape2Error = StartScrape2Errors[keyof StartScrape2Errors];

export type StartScrape2Responses = {
    /**
     * Successful Response
     */
    200: StartScrapeResponse;
};

export type StartScrape2Response = StartScrape2Responses[keyof StartScrape2Responses];

export type StopScrapeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/scrape/stop';
};

export type StopScrapeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetScrapeStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/scrape/status';
};

export type GetScrapeStatusResponses = {
    /**
     * Successful Response
     */
    200: ScrapeStatusResponse;
};

export type GetScrapeStatusResponse = GetScrapeStatusResponses[keyof GetScrapeStatusResponses];

export type GetScrapeResultsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/scrape/results';
};

export type GetScrapeResultsResponses = {
    /**
     * Successful Response
     */
    200: ScrapeResultsResponse;
};

export type GetScrapeResultsResponse = GetScrapeResultsResponses[keyof GetScrapeResultsResponses];

export type CheckNetworkData = {
    /**
     * Body
     */
    body?: NetworkCheckRequest | null;
    path?: never;
    query?: never;
    url: '/api/v1/network/check';
};

export type CheckNetworkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckNetworkError = CheckNetworkErrors[keyof CheckNetworkErrors];

export type CheckNetworkResponses = {
    /**
     * Successful Response
     */
    200: NetworkCheckResponse;
};

export type CheckNetworkResponse = CheckNetworkResponses[keyof CheckNetworkResponses];

export type GetProxyStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/network/proxy';
};

export type GetProxyStatusResponses = {
    /**
     * Successful Response
     */
    200: ProxyStatus;
};

export type GetProxyStatusResponse = GetProxyStatusResponses[keyof GetProxyStatusResponses];

export type CropImageData = {
    body: CropRequest;
    path?: never;
    query?: never;
    url: '/api/v1/images/crop';
};

export type CropImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CropImageError = CropImageErrors[keyof CropImageErrors];

export type CropImageResponses = {
    /**
     * Successful Response
     */
    200: CropResponse;
};

export type CropImageResponse = CropImageResponses[keyof CropImageResponses];

export type PreviewImageData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Path
         */
        path: string;
        /**
         * Width
         */
        width?: number | null;
        /**
         * Height
         */
        height?: number | null;
    };
    url: '/api/v1/images/preview';
};

export type PreviewImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewImageError = PreviewImageErrors[keyof PreviewImageErrors];

export type PreviewImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddWatermarkData = {
    body: WatermarkRequest;
    path?: never;
    query?: never;
    url: '/api/v1/images/watermark';
};

export type AddWatermarkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddWatermarkError = AddWatermarkErrors[keyof AddWatermarkErrors];

export type AddWatermarkResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetImageInfoData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/api/v1/images/info';
};

export type GetImageInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetImageInfoError = GetImageInfoErrors[keyof GetImageInfoErrors];

export type GetImageInfoResponses = {
    /**
     * Successful Response
     */
    200: ImageInfoResponse;
};

export type GetImageInfoResponse = GetImageInfoResponses[keyof GetImageInfoResponses];

export type FindMissingData = {
    body: FindMissingBody;
    path?: never;
    query?: never;
    url: '/api/v1/tools/find-missing';
};

export type FindMissingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FindMissingError = FindMissingErrors[keyof FindMissingErrors];

export type FindMissingResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MoveVideosData = {
    body: MoveVideosBody;
    path?: never;
    query?: never;
    url: '/api/v1/tools/move-videos';
};

export type MoveVideosErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MoveVideosError = MoveVideosErrors[keyof MoveVideosErrors];

export type MoveVideosResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CleanFilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tools/clean-files';
};

export type CleanFilesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ManageExtrasData = {
    body: ExtrasBody;
    path?: never;
    query?: never;
    url: '/api/v1/tools/extras';
};

export type ManageExtrasErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ManageExtrasError = ManageExtrasErrors[keyof ManageExtrasErrors];

export type ManageExtrasResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ManageExtrafanartCopyData = {
    body: ExtrasBody;
    path?: never;
    query?: never;
    url: '/api/v1/tools/extrafanart-copy';
};

export type ManageExtrafanartCopyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ManageExtrafanartCopyError = ManageExtrafanartCopyErrors[keyof ManageExtrafanartCopyErrors];

export type ManageExtrafanartCopyResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ManageThemeVideosData = {
    body: ExtrasBody;
    path?: never;
    query?: never;
    url: '/api/v1/tools/theme-videos';
};

export type ManageThemeVideosErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ManageThemeVideosError = ManageThemeVideosErrors[keyof ManageThemeVideosErrors];

export type ManageThemeVideosResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};